fix failing to load a required file
```
[ 7350/17079] TestGemRequire#test_dash_i_beats_gems = 0.08 s
  2) Error:
TestGemRequire#test_dash_i_beats_gems:
NameError: uninitialized constant HELLO
    /Users/kazuaki-matsuo/Documents/github/hackaride/ruby/test/rubygems/test_require.rb:77:in `test_dash_i_beats_gems'
```